TOKEN = '1486784403:AAGskDwDe9QQgCucPrU-fTBL-NCncNlfAWQ'  # bot token

all_carts = {'static/2_heart.png': 2,
             'static/2_diamond.png': 2,
             'static/2_club.png': 2,
             'static/2_spade.png': 2,
             'static/3_heart.png': 3,
             'static/3_diamond.png': 3,
             'static/3_club.png': 3,
             'static/3_spade.png': 3,
             'static/4_heart.png': 4,
             'static/4_diamond.png': 4,
             'static/4_club.png': 4,
             'static/4_spade.png': 4,
             'static/6_heart.png': 6,
             'static/6_diamond.png': 6,
             'static/6_club.png': 6,
             'static/6_spade.png': 6,
             'static/7_heart.png': 7,
             'static/7_diamond.png': 7,
             'static/7_club.png': 7,
             'static/7_spade.png': 7,
             'static/8_heart.png': 8,
             'static/8_diamond.png': 8,
             'static/8_club.png': 8,
             'static/8_spade.png': 8,
             'static/9_heart.png': 9,
             'static/9_diamond.png': 9,
             'static/9_club.png': 9,
             'static/9_spade.png': 9,
             'static/10_heart.png': 10,
             'static/10_diamond.png': 10,
             'static/10_club.png': 10,
             'static/10_spade.png': 10,
             'static/11_heart.png': 11,
             'static/11_diamond.png': 11,
             'static/11_club.png': 11,
             'static/11_spade.png': 11}
